[GLOBAL]
pants_version = "2.18.1"

backend_packages = [
  "pants.backend.python"
]

[source]
root_patterns = [
  '/',
  '/lib/lib1/src'
]

[python]
interpreter_constraints = ["==3.8.*"]
enable_resolves = true
default_resolve = "resolver"

[python.resolves]
resolver = "main_lockfile.lock"
lib1_resolver = "lib/lib1/lib1_resolver.lock"
